kind: pipeline
type: ssh
name: default
workspace:
    path: /myproject
server:
    host:
      from_secret: host
    user:
      from_secret: username
    ssh_key:
      from_secret: ssh_key
steps:
    - name: install node and dependencies
      commands:
        - sudo curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash 
        - nvm install v12.18.3 -y
        - npm install 
        - npm install pm2 -g -y
        - pm2 start server.js

    - name: install nginx and reverse proxy
      commands:
        - apt install nginx -y
        - mv /myproject/nginx_conf/default /etc/nginx/sites-enabled/
        - service nginx restart